### ISSUE TITLE
Consider adding support for '.template' extension

### ISSUE THREAD

**Issue by chrstphrknwtn** [henrikruscon/nova-env#1]
I'm not actually sure how common it is, but in many of my projects I use `.env.template` rather than `.env.example`.

Perhaps you could add `template` to the [supported extensions](https://github.com/henrikdahl/nova-env/blob/1204c8662c86d9de1fe97d3405336f86c375bc03/ENV.novaextension/Syntaxes/ENV.xml#L13)?

**Comment by henrikruscon** [comment]
Is this the general use of [`.env.template`](https://3musketeers.io/docs/environment-variables.html#files-env-template-and-env-example)?

Because if that's the case then I need to handle the combo detector separately, right now it looks for key-value pairs, that won't match if the purpose of template is to only include the keys.

Thanks for the feedback!

**Comment by chrstphrknwtn** [comment]
I'm really not sure what the general use of `.env.template` is, however I did find [this doc](https://3musketeers.io/docs/environment-variables.html#files-env-template-and-env-example) that demonstrates a distinction between a template and an example, which is also consistent with how I use `env.template`.

```env
# env.template
VAR_A
VAR_B
```

```env
# env.example
VAR_A=a
VAR_B=b
```
